# Generated by Django 3.2.7 on 2023-04-19 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+917223962066', max_length=30, region=None, verbose_name='Phone Number')),
                ('about_me', models.TextField(default='Say somthign about your self', verbose_name='About Me')),
                ('license', models.CharField(blank=True, max_length=20, null=True, verbose_name='Real State License')),
                ('profile_photo', models.ImageField(default='/Downloads/c5.png', upload_to='', verbose_name='Profile Photot')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='Gender')),
                ('country', django_countries.fields.CountryField(default='IND', max_length=2, verbose_name='Country')),
                ('city', models.CharField(default='Indore', max_length=200, verbose_name='City')),
                ('is_buyer', models.BooleanField(default=False, help_text='Are you looking to buy a Property?', verbose_name='Buyer')),
                ('is_seller', models.BooleanField(default=False, help_text='Are you looking to sell a Property?', verbose_name='Seller')),
                ('is_agent', models.BooleanField(default=False, help_text='Are you an Agent?', verbose_name='Agent')),
                ('top_agent', models.BooleanField(default=False, verbose_name='Top agent')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('num_review', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of reviews')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
