# Generated by Django 3.2.7 on 2023-04-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Indore', max_length=25, verbose_name='City'),
        ),
    ]
