# Generated by Django 3.2.7 on 2023-04-25 19:49

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyViews',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=250, verbose_name='Ip address')),
            ],
            options={
                'verbose_name': 'Total Views on Property',
                'verbose_name_plural': 'Total Property views',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Property title')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True)),
                ('ref_code', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Properti refrens code')),
                ('description', models.TextField(default='Please add your property description', verbose_name='Property descriptio')),
                ('country', django_countries.fields.CountryField(default='IN', max_length=2, verbose_name='Country')),
                ('city', models.CharField(default='Indore', max_length=180, verbose_name='City')),
                ('postal_code', models.CharField(default=453112, max_length=144, verbose_name='Postel code')),
                ('street_address', models.CharField(default='Aedi avenue Indore', max_length=250, verbose_name='Street address')),
                ('property_number', models.IntegerField(default=112, validators=[django.core.validators.MinValueValidator], verbose_name='Property number')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Price')),
                ('tax', models.DecimalField(decimal_places=2, default=10, help_text='10% property tax charged', max_digits=6, verbose_name='Property tax')),
                ('plot_area', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Plot area(m^2)')),
                ('total_floors', models.IntegerField(default=0, verbose_name='Number of floors')),
                ('bedrooms', models.IntegerField(default=1, verbose_name='Bedrooms')),
                ('bathrooms', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Bathrooms')),
                ('advert_type', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('Auction', 'Auction')], default='For Sale', max_length=60, verbose_name='Advert type')),
                ('property_type', models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Office', 'Office'), ('Warehouse', 'Warehouse'), ('Commercial', 'Commercial'), ('Other', 'Other')], default='House', max_length=80, verbose_name='Property_type')),
                ('cover_photo', models.ImageField(blank=True, default='c5.png', null=True, upload_to='', verbose_name='Main property photo')),
                ('photo1', models.ImageField(blank=True, default='c5.png', null=True, upload_to='')),
                ('photo2', models.ImageField(blank=True, default='c5.png', null=True, upload_to='')),
                ('photo3', models.ImageField(blank=True, default='c5.png', null=True, upload_to='')),
                ('photo4', models.ImageField(blank=True, default='c5.png', null=True, upload_to='')),
                ('published_status', models.BooleanField(default=False, verbose_name='Published statu')),
                ('views', models.IntegerField(default=0, verbose_name='Total views')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_buyer', to=settings.AUTH_USER_MODEL, verbose_name='Agent Seller or Buyer')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
