# Generated by Django 3.2.7 on 2023-04-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='published_status',
            field=models.BooleanField(default=False, verbose_name='Published status'),
        ),
    ]
