# Generated by Django 3.2.7 on 2023-04-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_published_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='ref_code',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Properti refrens code'),
        ),
    ]
