# Generated by Django 3.2.7 on 2023-04-29 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyviews',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='property_views', to='properties.property'),
            preserve_default=False,
        ),
    ]
